// <auto-generated />
using System;
using MediiProgramare_FitnessManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediiProgramare_FitnessManagement.Migrations
{
    [DbContext(typeof(MediiProgramare_FitnessManagementContext))]
    partial class MediiProgramare_FitnessManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.Booking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FitnessClassID")
                        .HasColumnType("int");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FitnessClassID");

                    b.HasIndex("MemberID");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.ClassType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("ClassType");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.FitnessClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ClassTypeID")
                        .HasColumnType("int");

                    b.Property<int?>("GymID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClassTypeID");

                    b.HasIndex("GymID");

                    b.HasIndex("TrainerID");

                    b.ToTable("FitnessClasses");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.Gym", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Gym");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.Trainer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Trainer");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.TrainerClassType", b =>
                {
                    b.Property<int>("TrainerID")
                        .HasColumnType("int");

                    b.Property<int>("ClassTypeID")
                        .HasColumnType("int");

                    b.HasKey("TrainerID", "ClassTypeID");

                    b.HasIndex("ClassTypeID");

                    b.ToTable("TrainerClassType");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.Booking", b =>
                {
                    b.HasOne("MediiProgramare_FitnessManagement.Models.FitnessClass", "Class")
                        .WithMany()
                        .HasForeignKey("FitnessClassID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediiProgramare_FitnessManagement.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.FitnessClass", b =>
                {
                    b.HasOne("MediiProgramare_FitnessManagement.Models.ClassType", "ClassType")
                        .WithMany()
                        .HasForeignKey("ClassTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediiProgramare_FitnessManagement.Models.Gym", "Gym")
                        .WithMany("Classes")
                        .HasForeignKey("GymID");

                    b.HasOne("MediiProgramare_FitnessManagement.Models.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassType");

                    b.Navigation("Gym");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.TrainerClassType", b =>
                {
                    b.HasOne("MediiProgramare_FitnessManagement.Models.ClassType", "ClassType")
                        .WithMany("TrainerClassTypes")
                        .HasForeignKey("ClassTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediiProgramare_FitnessManagement.Models.Trainer", "Trainer")
                        .WithMany("TrainerClassTypes")
                        .HasForeignKey("TrainerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassType");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.ClassType", b =>
                {
                    b.Navigation("TrainerClassTypes");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.Gym", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("MediiProgramare_FitnessManagement.Models.Trainer", b =>
                {
                    b.Navigation("TrainerClassTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
